"""Recreate schema from scratch

Revision ID: 58e5bccb3fff
Revises: 
Create Date: 2025-05-30 23:11:46.894443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e5bccb3fff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('user_id', sa.Integer(), nullable=True))  # Updated to nullable=True
    op.create_foreign_key(None, 'journal_entries', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('feedback_count', sa.Integer(), nullable=True))  # Updated to nullable=True
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'feedback_count')
    op.drop_constraint(None, 'journal_entries', type_='foreignkey')
    op.drop_column('journal_entries', 'user_id')
    # ### end Alembic commands ###
