"""Add is_premium to users

Revision ID: 6583b9524557
Revises: 16f8ac73d915
Create Date: 2025-06-06 15:19:58.305288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6583b9524557'
down_revision: Union[str, None] = '16f8ac73d915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_premium')
    # ### end Alembic commands ###
